import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { setTimeout as sleep } from 'node:timers/promises';
import { DbConnection } from '../../../packages/stdb-bindings/src/index.ts';
import { buildCohorts, loadConstants, runPlan } from '../../../packages/model/src/index.ts';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE_PATH);
const json = async file => JSON.parse(await readFile(file, 'utf8'));
const constants = loadConstants(await json('data/constants.json'));
const cohorts = buildCohorts(await json('data/cohort_spec.json'), constants.uaMeanBtuHPerF);
const scenario = await json('data/scenarios/feb2024.json');
const passcode = process.env.STDB_PASSCODE || (await readFile('stdb/HANDOFF.md', 'utf8')).match(/For `thermal-reserve-dev` it is `([^`]+)`/)[1];
const browser = await chromium.launch({ headless: true });
let connection;
try {
  const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('dialog', dialog => dialog.accept(passcode));
  await page.goto(`${process.env.WEB_URL || 'http://127.0.0.1:5173'}/ops?db=thermal-reserve-dev`);
  await page.getByText(/Connected · thermal-reserve-dev/).waitFor({ timeout: 30000 });
  await page.getByRole('button', { name: 'Demo preset', exact: true }).click();
  await page.getByText(/Operator; Start/).waitFor();
  await page.waitForFunction(() => !document.querySelector('.control-note')?.textContent.includes('Sending'));
  await page.getByLabel('Strategy', { exact: true }).selectOption('OPTIMIZED');
  await page.evaluate(() => { window.frameTimes = []; function frame(time) { window.frameTimes.push(time); window.frameTest = requestAnimationFrame(frame); } window.frameTest = requestAnimationFrame(frame); });
  const start = Date.now();
  await page.getByRole('button', { name: 'Solve plan', exact: true }).click();
  await page.getByRole('button', { name: 'System', exact: true }).click();
  assert(await page.getByText('Daily capacity ÷ 24 (average)', { exact: true }).isVisible(), 'Chart responds during solve');
  await page.waitForFunction(() => document.querySelector('.solve-status')?.textContent.startsWith('Optimized ·'), { timeout: 10000 });
  const solveMs = Date.now() - start;
  assert(solveMs < 5000, `Solve under 5 seconds: ${solveMs}`);
  const frames = await page.evaluate(() => { cancelAnimationFrame(window.frameTest); return window.frameTimes; });
  assert(frames.length >= 3, 'Animation frames continue during worker solve');
  assert(Math.max(...frames.slice(1).map((time, i) => time - frames[i])) < 500, 'No long main-thread solver stall');
  await page.getByRole('button', { name: 'Fleet', exact: true }).click();
  await page.getByRole('button', { name: 'Dispatch', exact: true }).click();
  await page.waitForFunction(() => !document.querySelector('.control-note')?.textContent.includes('Sending'));
  connection = await new Promise((resolve, reject) => {
    DbConnection.builder().withUri('wss://maincloud.spacetimedb.com').withDatabaseName('thermal-reserve-dev')
      .onConnect(conn => conn.subscriptionBuilder().onApplied(() => resolve(conn)).subscribe(['SELECT * FROM sim_config', 'SELECT * FROM plan_hour', 'SELECT * FROM aggregate_hour']))
      .onConnectError((_ctx, error) => reject(error)).build();
  });
  const config = [...connection.db.simConfig.iter()][0];
  assert.equal(config.strategy, 'OPTIMIZED');
  const targetsF = cohorts.map(() => Array(scenario.hours).fill(NaN));
  for (const target of connection.db.planHour.iter()) targetsF[target.cohortId][target.hour] = target.targetF;
  const cfg = { enrolledHomes: config.enrolledHomes, exemptShare: config.exemptShare, floorF: config.floorF, maxDepthF: config.maxDepthF, capacityMMcfd: config.capacityMmcfd, overrideRate: config.overrideRate, seed: 42 };
  const expected = runPlan(scenario, cohorts, cfg, { id: config.planId, strategy: config.strategy, targetsF }, constants);
  const speed = page.getByLabel('Speed', { exact: true }); await speed.focus(); await speed.press('End');
  await page.getByRole('button', { name: 'Apply inputs', exact: true }).click();
  await page.waitForFunction(() => !document.querySelector('.control-note')?.textContent.includes('Sending'));
  await page.getByRole('button', { name: 'Start', exact: true }).click();
  const deadline = Date.now() + 40000;
  while ([...connection.db.aggregateHour.iter()].length < scenario.hours && Date.now() < deadline) await sleep(100);
  const aggregates = [...connection.db.aggregateHour.iter()].sort((a, b) => a.hour - b.hour);
  assert.equal(aggregates.length, scenario.hours);
  const differences = aggregates.map(row => Math.abs(row.fleetGasMmcf - expected.hours[row.hour].fleetGasMMcfh) / Math.max(expected.hours[row.hour].fleetGasMMcfh, 1e-9));
  assert(Math.max(...differences) <= 0.05, `Live differs by ${Math.max(...differences) * 100}%`);
  const chart = await page.locator('.fleet-panel').boundingBox(); assert(chart.y + chart.height <= 800);
  await page.screenshot({ path: '/tmp/thermal-reserve-w3-optimized.png', fullPage: true });
  assert.equal(errors.length, 0, errors.join('\n'));
  console.log(JSON.stringify({ acceptance: 'W3 PASS', solveMs, frames: frames.length, maxFrameGapMs: Math.max(...frames.slice(1).map((time, i) => time - frames[i])), hoursCompared: aggregates.length, maxRelativeError: Math.max(...differences) }));
  await page.getByRole('button', { name: 'Reset', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('.clock-status')?.textContent.includes('idle'));
  const enrollment = page.getByLabel('Enrolled homes', { exact: true });
  await enrollment.focus(); await enrollment.press('ArrowLeft');
  assert(await page.getByRole('button', { name: 'Dispatch', exact: true }).isDisabled(), 'Changed inputs invalidate the solved plan');
  const fallbackPage = await browser.newPage({ viewport: { width: 1280, height: 800 } });
  await fallbackPage.route('**/*.wasm', route => route.abort());
  await fallbackPage.goto(`${process.env.WEB_URL || 'http://127.0.0.1:5173'}/ops?db=thermal-reserve-dev`);
  await fallbackPage.getByText(/Connected · thermal-reserve-dev/).waitFor({ timeout: 30000 });
  await fallbackPage.getByLabel('Strategy', { exact: true }).selectOption('MAX_RELIEF');
  await fallbackPage.getByRole('button', { name: 'Solve plan', exact: true }).click();
  await fallbackPage.getByText('Rule-based fallback in use · Staggered', { exact: true }).waitFor({ timeout: 10000 });
  assert(await fallbackPage.getByRole('button', { name: 'Dispatch', exact: true }).isEnabled(), 'Fallback plan can be dispatched');
  console.log(JSON.stringify({ fallback: 'PASS', stalePlanInvalidation: 'PASS' }));
} finally { connection?.disconnect(); await browser.close(); }
