import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE_PATH);
const url = process.env.WEB_URL || 'http://127.0.0.1:5175';
const passcode = process.env.STDB_PASSCODE || (await readFile('stdb/HANDOFF.md', 'utf8')).match(/For `thermal-reserve-dev` it is `([^`]+)`/)[1];
const browser = await chromium.launch({ headless: true });
const errors = [];
try {
  const ops = await browser.newPage({ viewport: { width: 1280, height: 800 } });
  ops.on('pageerror', error => errors.push(error.message));
  await ops.route('https://tile.openstreetmap.org/**', route => route.abort());
  ops.on('dialog', dialog => dialog.accept(passcode));
  await ops.goto(`${url}/ops?db=thermal-reserve-dev`);
  await ops.getByText(/Connected · thermal-reserve-dev/).waitFor({ timeout: 30000 });
  await ops.getByRole('button', { name: 'Demo preset', exact: true }).click();
  await ops.getByText(/Connected · thermal-reserve-dev · Operator/).waitFor();
  await ops.waitForFunction(() => !document.querySelector('.control-note')?.textContent.includes('Sending'));
  await ops.getByRole('button', { name: 'Reset households', exact: true }).click();
  await ops.waitForFunction(() => !document.querySelector('.control-note')?.textContent.includes('Sending'));
  await ops.getByRole('button', { name: 'Enlarge household join QR code' }).click();
  const qr = ops.getByRole('dialog');
  assert(await qr.isVisible());
  assert((await qr.locator('a').getAttribute('href')).startsWith(`${url}/home`));
  await qr.getByRole('button', { name: 'Close', exact: true }).click();
  const phones = [];
  const enrollmentMs = [];
  for (const [name, steady, width] of [['W4 Phone A', false, 390], ['W4 Steady B', true, 360]]) {
    const context = await browser.newContext({ viewport: { width, height: 844 }, isMobile: true, hasTouch: true });
    const phone = await context.newPage(); phones.push(phone);
    phone.on('pageerror', error => errors.push(error.message));
    await phone.goto(`${url}/home?db=thermal-reserve-dev`);
    const start = Date.now();
    await phone.getByRole('button', { name: 'Join as an Anchorage home', exact: true }).click();
    await phone.getByLabel('Nickname (optional)', { exact: true }).fill(name);
    if (steady) await phone.getByRole('checkbox').check();
    await phone.getByRole('button', { name: 'Continue', exact: true }).click();
    if (!steady) assert(await phone.getByText(/never below 62°F/).isVisible());
    await phone.getByRole('button', { name: 'Join', exact: true }).click();
    await phone.getByRole('heading', { name, exact: true }).waitFor();
    enrollmentMs.push(Date.now() - start);
    assert(enrollmentMs.at(-1) < 20000, 'Enroll within 20 seconds');
    const joinedAt = Date.now();
    await ops.locator('.map-fallback circle title').filter({ hasText: name }).waitFor({ state: 'attached' });
    assert(Date.now() - joinedAt < 2000, 'Home appears on map within 2 seconds');
    await phone.waitForFunction(() => document.documentElement.scrollWidth <= window.innerWidth);
  }
  await ops.getByRole('button', { name: 'Start', exact: true }).click();
  await phones[0].locator('.heat-status').filter({ hasText: 'Holding' }).waitFor({ timeout: 20000 });
  assert.equal(await phones[1].locator('.heat-status').innerText(), 'Exempt');
  assert.equal(await phones[1].getByRole('button', { name: 'Override', exact: true }).count(), 0);
  await phones[0].getByRole('button', { name: 'Override', exact: true }).click();
  await phones[0].getByRole('button', { name: 'Rejoin event', exact: true }).waitFor();
  assert.equal(await phones[0].locator('.heat-status').innerText(), 'Overridden');
  assert((await phones[0].locator('.setpoint').innerText()).includes('70.0°F'));
  await ops.locator('.event-list').getByText('W4 Phone A overrode: normal heat restored', { exact: true }).waitFor({ timeout: 2000 });
  await ops.locator('.event-list').getByText("W4 Phone A's setback reassigned across participating homes", { exact: true }).waitFor({ timeout: 2000 });
  await phones[0].reload();
  await phones[0].getByRole('heading', { name: 'W4 Phone A', exact: true }).waitFor();
  await phones[0].getByRole('button', { name: 'Rejoin event', exact: true }).click();
  await phones[0].getByRole('button', { name: 'Override', exact: true }).waitFor();
  await ops.getByRole('button', { name: 'Pause', exact: true }).click();
  const log = await ops.locator('.log-panel').boundingBox();
  const footer = await ops.locator('.app-footer').boundingBox();
  assert(log.y + log.height <= footer.y, 'Event log does not overlap honesty footer');
  assert(await ops.evaluate(() => document.documentElement.scrollHeight <= 800));
  await phones[0].screenshot({ path: '/tmp/thermal-reserve-w4-home.png', fullPage: true });
  await ops.screenshot({ path: '/tmp/thermal-reserve-w4-ops.png', fullPage: true });
  assert.equal(errors.length, 0, errors.join('\n'));
  console.log(JSON.stringify({ browserChecks: 'W4 PASS (emulated phones; real phones pending)', enrollmentMs, households: 2, overrideLog: true, reassignmentLog: true, reloadPersistence: true, footerClear: true, pageErrors: errors }));
  await ops.getByRole('button', { name: 'Reset households', exact: true }).click();
  await phones[0].getByRole('button', { name: 'Join as an Anchorage home', exact: true }).waitFor();
  await ops.getByRole('button', { name: 'Reset', exact: true }).click();
} finally { await browser.close(); }
