import { Area, CartesianGrid, ComposedChart, Line, ReferenceArea, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { Scenario } from '@thermal-reserve/model';
import { clockLabel, integer, temperature } from '../lib/ops';
import { ChartTooltip, tooltipProps } from './ChartTooltip';
export interface DiscomfortRow { hour: number; active?: number; worst?: number; naive: number; staggered?: number; /* ignored: Staggered is no longer drawn */ }
export function DiscomfortChart({ rows, scenario, maxDepthF, degreeHours, minIndoorF, holdingHours }: { rows: DiscomfortRow[]; scenario: Scenario; maxDepthF: number; degreeHours?: number; minIndoorF?: number; holdingHours?: number }) {
  return <figure className="panel discomfort-chart"><h2>3 · Home discomfort <span className="metric-label">derived · modeled</span></h2>
    <div className="pressure-plot"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={rows} syncId="pressure-clock" margin={{ top: 16, right: 20, bottom: 14, left: 8 }} accessibilityLayer>
      <CartesianGrid stroke="var(--border)" strokeDasharray="3 3" /><XAxis dataKey="hour" type="number" domain={[0, scenario.hours]} ticks={[0, 24, 48, 72, scenario.hours]} stroke="var(--muted)" tick={{ fontSize: 9 }} tickFormatter={h => clockLabel(scenario, Number(h)).replace(/, /g, ' ')} label={{ value: 'Anchorage time', position: 'bottom', fill: 'var(--muted)', fontSize: 10 }} /><YAxis domain={[0, maxDepthF + 1]} width={58} tick={{ fontSize: 10 }} stroke="var(--muted)" label={{ value: '°F below preferred', angle: -90, position: 'insideLeft', style: { textAnchor: 'middle' }, fill: 'var(--muted)', fontSize: 10 }} />
      <Tooltip {...tooltipProps} content={props => <ChartTooltip {...props} scenario={scenario} line={entry => <>{entry.name}: {temperature.format(Number(entry.value))}°F below no program</>} />} />
      <ReferenceArea x1={scenario.eventStartHour} x2={scenario.eventEndHour} fill="#5BC0EB" fillOpacity={0.05} /><ReferenceLine y={maxDepthF} stroke="#7A869A" strokeDasharray="3 3" />
      <Area name="Selected plan mean" dataKey="active" fill="#5BC0EB" fillOpacity={0.2} stroke="#5BC0EB" isAnimationActive={false} /><Line name="Coldest home type gap" dataKey="worst" stroke="#E6EDF7" strokeWidth={1} dot={false} isAnimationActive={false} /><Line name="Naive 4-hour" dataKey="naive" stroke="#F2A541" strokeDasharray="5 3" dot={false} isAnimationActive={false} />
    </ComposedChart></ResponsiveContainer></div><figcaption>{degreeHours === undefined ? 'Solve to see the selected plan’s discomfort.' : holdingHours ? `${integer.format(degreeHours)} °F·h/home: about ${temperature.format(degreeHours / holdingHours)}°F cooler across ${holdingHours} setback hours.` : `${integer.format(degreeHours)} °F·h/home.`} {minIndoorF !== undefined && `No home below ${temperature.format(minIndoorF)}°F.`}</figcaption></figure>;
}
