// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CancelOverrideReducer from "../cancel_override_reducer";
import ClaimOperatorReducer from "../claim_operator_reducer";
import JoinHouseholdReducer from "../join_household_reducer";
import LoadHomesReducer from "../load_homes_reducer";
import LoadScenarioReducer from "../load_scenario_reducer";
import OverrideReducer from "../override_reducer";
import PauseReducer from "../pause_reducer";
import ResetReducer from "../reset_reducer";
import ResetHouseholdsReducer from "../reset_households_reducer";
import SetParamsReducer from "../set_params_reducer";
import SetPlanReducer from "../set_plan_reducer";
import StartReducer from "../start_reducer";

export type CancelOverrideParams = __Infer<typeof CancelOverrideReducer>;
export type ClaimOperatorParams = __Infer<typeof ClaimOperatorReducer>;
export type JoinHouseholdParams = __Infer<typeof JoinHouseholdReducer>;
export type LoadHomesParams = __Infer<typeof LoadHomesReducer>;
export type LoadScenarioParams = __Infer<typeof LoadScenarioReducer>;
export type OverrideParams = __Infer<typeof OverrideReducer>;
export type PauseParams = __Infer<typeof PauseReducer>;
export type ResetParams = __Infer<typeof ResetReducer>;
export type ResetHouseholdsParams = __Infer<typeof ResetHouseholdsReducer>;
export type SetParamsParams = __Infer<typeof SetParamsReducer>;
export type SetPlanParams = __Infer<typeof SetPlanReducer>;
export type StartParams = __Infer<typeof StartReducer>;

