// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  hour: __t.u32().primaryKey(),
  fleetGasMmcf: __t.f64().name("fleet_gas_mmcf"),
  baselineGasMmcf: __t.f64().name("baseline_gas_mmcf"),
  systemMmcf: __t.f64().name("system_mmcf"),
  capacityMmcf: __t.f64().name("capacity_mmcf"),
  reliefMmcf: __t.f64().name("relief_mmcf"),
  minTaF: __t.f64().name("min_ta_f"),
  shareAtFloor: __t.f64().name("share_at_floor"),
  overrides: __t.u32(),
  households: __t.u32(),
  strategy: __t.string(),
});
