// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  cohortId: __t.u32().primaryKey().name("cohort_id"),
  taF: __t.f64().name("ta_f"),
  tmF: __t.f64().name("tm_f"),
  qBtuh: __t.f64().name("q_btuh"),
  targetF: __t.f64().name("target_f"),
  baseTaF: __t.f64().name("base_ta_f"),
  baseTmF: __t.f64().name("base_tm_f"),
  gasCfThisHour: __t.f64().name("gas_cf_this_hour"),
  baseGasCfThisHour: __t.f64().name("base_gas_cf_this_hour"),
  overriddenShare: __t.f64().name("overridden_share"),
  mode: __t.string(),
});
