// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  key: __t.string(),
  heating: __t.string(),
  share: __t.f64(),
  ua: __t.f64(),
  uao: __t.f64(),
  umo: __t.f64(),
  ham: __t.f64(),
  ca: __t.f64(),
  cm: __t.f64(),
  qmaxBtuh: __t.f64().name("qmax_btuh"),
  eta: __t.f64(),
  setpointDayF: __t.f64().name("setpoint_day_f"),
  setpointNightF: __t.f64().name("setpoint_night_f"),
  nightStartHour: __t.u32().name("night_start_hour"),
  nightEndHour: __t.u32().name("night_end_hour"),
});
