// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  nickname: __t.string(),
  heating: __t.string(),
  thermostat: __t.string(),
  exempt: __t.bool(),
  floorF: __t.f64().name("floor_f"),
  cohortId: __t.u32().name("cohort_id"),
  lat: __t.f64(),
  lon: __t.f64(),
  taF: __t.f64().name("ta_f"),
  tmF: __t.f64().name("tm_f"),
  baseTaF: __t.f64().name("base_ta_f"),
  baseTmF: __t.f64().name("base_tm_f"),
  targetF: __t.f64().name("target_f"),
  overridden: __t.bool(),
  savedCf: __t.f64().name("saved_cf"),
  joinedAt: __t.timestamp().name("joined_at"),
  online: __t.bool(),
});
