// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  scenarioId: __t.string().name("scenario_id"),
  status: __t.string(),
  simHour: __t.f64().name("sim_hour"),
  speedHoursPerSec: __t.f64().name("speed_hours_per_sec"),
  strategy: __t.string(),
  planId: __t.string().name("plan_id"),
  enrolledHomes: __t.u32().name("enrolled_homes"),
  exemptShare: __t.f64().name("exempt_share"),
  floorF: __t.f64().name("floor_f"),
  maxDepthF: __t.f64().name("max_depth_f"),
  capacityMmcfd: __t.f64().name("capacity_mmcfd"),
  overrideRate: __t.f64().name("override_rate"),
  hours: __t.u32(),
  eventStartHour: __t.u32().name("event_start_hour"),
  eventEndHour: __t.u32().name("event_end_hour"),
  homesPerDot: __t.f64().name("homes_per_dot"),
  operator: __t.option(__t.identity()),
  updatedAt: __t.timestamp().name("updated_at"),
});
