// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AggregateHour = __t.object("AggregateHour", {
  hour: __t.u32(),
  fleetGasMmcf: __t.f64(),
  baselineGasMmcf: __t.f64(),
  systemMmcf: __t.f64(),
  capacityMmcf: __t.f64(),
  reliefMmcf: __t.f64(),
  minTaF: __t.f64(),
  shareAtFloor: __t.f64(),
  overrides: __t.u32(),
  households: __t.u32(),
  strategy: __t.string(),
});
export type AggregateHour = __Infer<typeof AggregateHour>;

export const Cohort = __t.object("Cohort", {
  id: __t.u32(),
  key: __t.string(),
  heating: __t.string(),
  share: __t.f64(),
  ua: __t.f64(),
  uao: __t.f64(),
  umo: __t.f64(),
  ham: __t.f64(),
  ca: __t.f64(),
  cm: __t.f64(),
  qmaxBtuh: __t.f64(),
  eta: __t.f64(),
  setpointDayF: __t.f64(),
  setpointNightF: __t.f64(),
  nightStartHour: __t.u32(),
  nightEndHour: __t.u32(),
});
export type Cohort = __Infer<typeof Cohort>;

export const CohortState = __t.object("CohortState", {
  cohortId: __t.u32(),
  taF: __t.f64(),
  tmF: __t.f64(),
  qBtuh: __t.f64(),
  targetF: __t.f64(),
  baseTaF: __t.f64(),
  baseTmF: __t.f64(),
  gasCfThisHour: __t.f64(),
  baseGasCfThisHour: __t.f64(),
  overriddenShare: __t.f64(),
  mode: __t.string(),
});
export type CohortState = __Infer<typeof CohortState>;

export const EventLog = __t.object("EventLog", {
  id: __t.u64(),
  simHour: __t.f64(),
  kind: __t.string(),
  message: __t.string(),
  at: __t.timestamp(),
});
export type EventLog = __Infer<typeof EventLog>;

export const Household = __t.object("Household", {
  identity: __t.identity(),
  nickname: __t.string(),
  heating: __t.string(),
  thermostat: __t.string(),
  exempt: __t.bool(),
  floorF: __t.f64(),
  cohortId: __t.u32(),
  lat: __t.f64(),
  lon: __t.f64(),
  taF: __t.f64(),
  tmF: __t.f64(),
  baseTaF: __t.f64(),
  baseTmF: __t.f64(),
  targetF: __t.f64(),
  overridden: __t.bool(),
  savedCf: __t.f64(),
  joinedAt: __t.timestamp(),
  online: __t.bool(),
});
export type Household = __Infer<typeof Household>;

export const OperatorSecret = __t.object("OperatorSecret", {
  id: __t.u32(),
  passcode: __t.string(),
});
export type OperatorSecret = __Infer<typeof OperatorSecret>;

export const PlanHour = __t.object("PlanHour", {
  id: __t.u64(),
  planId: __t.string(),
  cohortId: __t.u32(),
  hour: __t.u32(),
  targetF: __t.f64(),
});
export type PlanHour = __Infer<typeof PlanHour>;

export const SampleHome = __t.object("SampleHome", {
  id: __t.u32(),
  cohortId: __t.u32(),
  lat: __t.f64(),
  lon: __t.f64(),
  exempt: __t.bool(),
  overrideHour: __t.f64(),
  overridden: __t.bool(),
});
export type SampleHome = __Infer<typeof SampleHome>;

export const SimConfig = __t.object("SimConfig", {
  id: __t.u32(),
  scenarioId: __t.string(),
  status: __t.string(),
  simHour: __t.f64(),
  speedHoursPerSec: __t.f64(),
  strategy: __t.string(),
  planId: __t.string(),
  enrolledHomes: __t.u32(),
  exemptShare: __t.f64(),
  floorF: __t.f64(),
  maxDepthF: __t.f64(),
  capacityMmcfd: __t.f64(),
  overrideRate: __t.f64(),
  hours: __t.u32(),
  eventStartHour: __t.u32(),
  eventEndHour: __t.u32(),
  homesPerDot: __t.f64(),
  operator: __t.option(__t.identity()),
  updatedAt: __t.timestamp(),
  startIso: __t.string(),
  hhvBtuPerCf: __t.f64(),
});
export type SimConfig = __Infer<typeof SimConfig>;

export const TickSchedule = __t.object("TickSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TickSchedule = __Infer<typeof TickSchedule>;

export const WeatherHour = __t.object("WeatherHour", {
  hour: __t.u32(),
  outdoorF: __t.f64(),
  systemMmcfh: __t.f64(),
});
export type WeatherHour = __Infer<typeof WeatherHour>;

